---
- name: Create Docker Container
  hosts: 172.31.14.211
  user: docker
  become: yes
  tasks:
    - name: include variables
      include_vars: vars.yml
    - name: Create Container
      docker:
        name: "{{ name }}"
        image: "{{ image }}"
        ports:
          - "{{ src_port }}:{{ dest_port }}"
        volumes:
          - "{{ src_vol }}:{{ dest_vol }}"
        privileged: "{{ privileged }}"
    - name: Create samplej2 Unit File as docker-{{ name }}.service
      template: src=sample.j2 dest=/etc/systemd/system/docker-{{ name }}.service
    - name: reload systemd daemon
      command: systemctl daemon-reload 
    - name: Start & Enable docker-{{ name }} service
      service:
        name: docker-{{ name }}
        state: started
        enabled: yes
    - name: check container status
      command: docker ps
      register: result
    - debug: var=result.stdout