---
- name: Build an image with the docker_image module
  hosts: 172.31.14.211
  remote_user: docker
  become: yes
  tasks:
    - name: upload the site directory to the docker host
      synchronize: src=site dest=/tmp

    - name: build the image
      docker_image: >
        name=ansiblebuiltit
        tag=ex1
        path=/tmp/site
        state=present
    - name: run the site in a docker container
      docker:
        name: site1
        image: "ansiblebuiltit:ex1"
        state: reloaded
        publish_all_ports: yes
