 
- hosts: localhost ansible_connection=local
  user: ec2-user
  become: yes
  tasks:
    - name: Date and Time the playbook started
      command: date
      register: timestamp_start
    - debug: var=timestamp_start
    - name: Install lynx
      yum: pkg=lynx state=latest
    - name: Install telnet
      yum: pkg=telnet state=latest