---
- hosts: all
  become: yes
  tasks:
    - name: display hostname
      command: hostname
    - name: Date and Time the playbook started
      command: date
      register: timestamp_start
    - debug: var=timestamp_start
    - name: unInstall wget
      yum: pkg=wget state=absent
    - name: Install telnet
      yum: pkg=telnet state=latest