---
- hosts: 172.31.14.211
  user: docker
  become: yes
  gather_facts: yes
  tasks:
  - name: install docker-py using PIP
    pip:
     name: docker-py
     state: present
  - name: stop docker containers
    docker:
     image: nimmis/apache-php5
     state: stopped
  - name: remove docker containers
    docker:
      image: nimmis/apache-php5
      state: absent
  - name: Remove nimmis image
    docker_image:
     name: nimmis/apache-php5
     state: absent