---
- name: Build an image with the docker_image module
  hosts: 172.31.14.211
  remote_user: docker
  become: yes
  tasks:
    - name: upload the dockerfile to the docker host
      synchronize: src=Dockerfile dest=/tmp

    - name: build the image
      docker_image: >
        name=centos/apache
        tag=rt1
        path=/tmp/
        state=present

    - name: Create a container with above image
      command: docker run -d --name apacheweb1 -p 8080:80  centos/apache:rt1
